name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Docker image
      run: docker compose up -d
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Publish Docker image
      run: |
        docker build -t poke-app:latest .
        docker tag poke-app:latest fabrien/poke-app:latest
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push fabrien/poke-app:latest
