name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Run tests with Vitest
      run: npm run vitest
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Run Docker image
      run: docker compose up -d
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Tag and Push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Récupérer tous les tags existants et vérifier s'il y en a
        TAGS=$(git tag)
        if [ -z "$TAGS" ]; then
          echo "Aucun tag trouvé. Initialisation à 0.1.0."
          NEW_TAG="0.1.0"
        else
          # Récupérer le dernier tag basé sur le versioning sémantique
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          # Incrémente le patch version
          NEW_TAG=$(echo $LAST_TAG | awk -F. -v OFS=. '{$NF = $NF + 1; print}')
        fi

        docker build -t poke-app:$NEW_TAG .
        docker tag poke-app:$NEW_TAG fabrien/poke-app:$NEW_TAG

        # Se connecter à Docker Hub
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

        # Pousser l'image vers Docker Hub avec le nouveau tag
        docker push fabrien/poke-app:$NEW_TAG

        # Configurer les informations de l'utilisateur Git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Créer le nouveau tag et le pousser
        git tag $NEW_TAG
        git push https://${GITHUB_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.git $NEW_TAG

        echo "Nouveau tag créé et poussé sur Docker Hub et GitHub: $NEW_TAG"
