name: Docker Image CI

on:
  push:
    branches: [ '!main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Docker image
      run: docker compose up -d
